extraction:
  python:
    after_prepare:
      - pip install tomlkit -t ./vendor
      - PYTHONPATH=./vendor python3 ./scripts/requirements.py
      - rm -r ./vendor

    python_setup:
      version: 3
      requirements_files:
        - requirements.txt
      setup_py: false
